import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import Logo from '../components/icons/logo/Logo';
import SearchBar from '../components/MainSection/SearchBar/SearchBar';
import styles from '../styles/index.module.css';

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Umbrella</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <div
        style={{
          display: 'flex',
          flexDirection: 'column',
          justifyContent: 'center',
          alignItems: 'center',
          height: '100%',
          width: '100%',
        }}
      >
        <Logo width={300} height={100} />
        <SearchBar
          style={{ position: 'relative', justifyContent: 'center' }}
          type='main'
          status={200}
        />
      </div>
    </>
  );
};

export default Home;
